spring:
  profiles:
    active: postgres

  application:
    name: aws-postgres-connect

# Swagger LOCAL Url http://192.168.31.1:8080/swagger-ui/index.html
#                       OR
# Swagger AWS Url http://<your-ec2-or-loadbalancer>:80/swagger-ui/index.html