spring:
  application:
    name: aws-postgres-connect

  # jdbc:postgressql://<public_dns>:<pot>/<db-name>
  datasource:
#   My Local postgres DB
#    url: jdbc:postgresql://localhost:5432/postgres
#   AWS RDS postgres DB
    url: jdbc:postgresql://aws-rds-postgres-instance.cdkw246sgazm.ap-south-1.rds.amazonaws.com:5432/postgres
    username: postgres
#    password: root
    password: root123456
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sal: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
# Swagger LOCAL Url http://192.168.31.1:8080/swagger-ui/index.html
# or
# Swagger AWS Url http://<your-ec2-or-loadbalancer>:80/swagger-ui/index.html